### ISSUE TITLE
Lab 5 - Review

### ISSUE THREAD

**Issue by viktorfrom** [Decending/D7020E_lab5#1]
get_sign.c - I believe the answers have been mixed up [here](https://github.com/Decending/D7020E_lab5/blob/4e60e28945cf95dfdc96ceba69bc343e3d833766/examples/get_sign.c#L62), the order should be first, third and second path.

get_sign.rs - Same [here](https://github.com/Decending/D7020E_lab5/blob/4e60e28945cf95dfdc96ceba69bc343e3d833766/examples/get_sign.rs#L163), the order should be third, first and second path.

array.rs - [Here](https://github.com/Decending/D7020E_lab5/blob/4e60e28945cf95dfdc96ceba69bc343e3d833766/cargo_klee_examples/examples/array.rs#L51) I believe the answer to the number of tests we get (10x) has to do with the length of the array (=8) and ensuring the values are not out of index (0 and 255). I could be wrong though, merely speculative. [Here](https://github.com/Decending/D7020E_lab5/blob/4e60e28945cf95dfdc96ceba69bc343e3d833766/cargo_klee_examples/examples/array.rs#L61) almost got it, try moving the if-statement inside the loop instead.  Missing answers for D), E) and F).

cyccnt.rs - [Missing answer](https://github.com/Decending/D7020E_lab5/blob/4e60e28945cf95dfdc96ceba69bc343e3d833766/cargo_klee_examples/examples/cyccnt.rs#L210). [Here](https://github.com/Decending/D7020E_lab5/blob/4e60e28945cf95dfdc96ceba69bc343e3d833766/cargo_klee_examples/examples/cyccnt.rs#L242) I believe the questions refer to the cycle counter code above. It's just some general questions.

Other than that I can't seem to find anything.

**Comment by Decending** [comment]
I've addressed these issues now, you were correct in that I had messed up the order in which I wrote the tests, but we seem to have gotten a different order on our tests as well.
   If there are any remaining issues in the code, add a comment here. If I don't hear from you I'll close this issue before heading to bed.
