### ISSUE TITLE
Lab 5 review

### ISSUE THREAD

**Issue by rubenasplund** [Decending/D7020E_lab5#2]
example/get_sign.c - Looks good!

example/get_sign.rs - Looks good!

cargo_klee_examples/examples/array.rs - Answers on line 76, 81, 91 is missing

cargo_klee_examples/examples/cyccnt.rs - Answers on line 209, 243 is missing.

cargo_klee_examples/examples/get_sign.rs - Looks good!

**Comment by Decending** [comment]
I've addressed these issues now, if there's anything I've missed mention it in a comment here during the day.
If I don't hear from you I'll close this issue before going to bed.
